### ISSUE TITLE
luaplus.org is down

### ISSUE THREAD

**Issue by cinterloper** [jjensen/luaplus51-all#12]
```
Web application could not be started

exit (SystemExit)
  /home/joshuajensen/luaplus.org/config/boot.rb:66:in `exit'
  /home/joshuajensen/luaplus.org/config/boot.rb:66:in `rescue in load_rails_gem'
  /home/joshuajensen/luaplus.org/config/boot.rb:59:in `load_rails_gem'
  /home/joshuajensen/luaplus.org/config/boot.rb:54:in `load_initializer'
  /home/joshuajensen/luaplus.org/config/boot.rb:38:in `run'
  /home/joshuajensen/luaplus.org/config/boot.rb:11:in `boot!'
  /home/joshuajensen/luaplus.org/config/boot.rb:110:in `<top (required)>'
  /home/joshuajensen/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /home/joshuajensen/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /home/joshuajensen/luaplus.org/config/environment.rb:11:in `<top (required)>'
  /home/joshuajensen/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /home/joshuajensen/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /dh/passenger/helper-scripts/classic-rails-preloader.rb:96:in `preload_app'
  /dh/passenger/helper-scripts/classic-rails-preloader.rb:184:in `<module:App>'
  /dh/passenger/helper-scripts/classic-rails-preloader.rb:29:in `<module:PhusionPassenger>'
  /dh/passenger/helper-scripts/classic-rails-preloader.rb:28:in `<main>'

Error ID
    0893af76
```

maybe time for a lua webserver? (;

**Comment by jjensen** [comment]
I have made http://luaplus.org redirect to the GitHub page. DreamHost is excellent at killing Rails sites with their upgrades. :(
